# Opt into Ubuntu 14 for newer Pango version.
sudo: required
dist: trusty

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatk1.0-dev libpango1.0-dev

language: rust
cache: cargo
