[package]
name = "smash"
version = "0.1.0"
authors = ["Evan Martin <martine@danga.com>"]

[dependencies]
cairo-rs = "^0"
glib = "^0"
gdk = "^0"
libc = "0.2.11"

[dependencies.gtk]
version = "0.0.7"
features = ["v3_8", "embed-lgpl-docs"]
